#!/usr/bin/env python3
"""
Test Task 5 to Task 1 integration workflow
"""

import sys
sys.path.append('/home/pauljcoles/code/cats/task-manager')

from src.validation.task1_integration import execute_task_1_for_ticket

def test_task5_to_task1_workflow():
    """Test that Task 5 generated stories work with Task 1 validation"""
    
    print("🧪 Testing Task 5 → Task 1 Workflow")
    print("=" * 60)
    
    # Test a story generated by Task 5
    story_id = "SPECBROADBAND-003-STORY-001"
    
    print(f"📋 Testing story generated by Task 5: {story_id}")
    
    try:
        # Run Task 1 validation on Task 5 generated story
        context = execute_task_1_for_ticket(story_id)
        
        if context:
            print(f"\n✅ Task 1 validation completed successfully!")
            print(f"   Score: {context.eval_result.score:.2f}/100")
            print(f"   Issues: {context.eval_result.total_issues}")
            print(f"   Status: {'PASSED' if context.eval_result.passed else 'FAILED'}")
            
            return True
        else:
            print(f"\n❌ Task 1 validation failed to complete")
            return False
        
    except Exception as e:
        print(f"❌ Error during Task 1 validation: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_task5_to_task1_workflow()
    sys.exit(0 if success else 1)